name: wonderpress-coding-standards

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  wonderpress-coding-standards:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer
        coverage: none
    - name: Codesniff against the Wonderpress Coding Standards...
      run: composer update && composer run lint
